


import win32com.client as win32

outlook = win32.Dispatch('outlook.application')
mail = outlook.CreateItem(0)
mail.To = '13072993790@163.com'

mail.Subject = "test"
mail.Body = 'Message body'
mail.HTMLBody = '''<h2>This is an email auto-generated by program</h2><h3>Sapphire's list</h3>''' #this field is optional

# To attach a file to the email (optional):
# attachment  = "Path to the attachment"
# mail.Attachments.Add(attachment)

mail.Send()